// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqdYE8anvzSzh6MvIcxUM8MYPDeEcPAmY',
    appId: '1:235732561156:web:b11bec2a3c93937b177451',
    messagingSenderId: '235732561156',
    projectId: 'haber-cepte-b7666',
    authDomain: 'haber-cepte-b7666.firebaseapp.com',
    storageBucket: 'haber-cepte-b7666.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLbBCCYtCAdnZRPy_QNY2RCr_4k1qE1VY',
    appId: '1:235732561156:android:be55dbe607677108177451',
    messagingSenderId: '235732561156',
    projectId: 'haber-cepte-b7666',
    storageBucket: 'haber-cepte-b7666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiTMaBVRhbjayVVTdMMg_qiIXq3Scav-g',
    appId: '1:235732561156:ios:78014474a3aee5b7177451',
    messagingSenderId: '235732561156',
    projectId: 'haber-cepte-b7666',
    storageBucket: 'haber-cepte-b7666.firebasestorage.app',
    iosBundleId: 'com.example.haberCepte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiTMaBVRhbjayVVTdMMg_qiIXq3Scav-g',
    appId: '1:235732561156:ios:78014474a3aee5b7177451',
    messagingSenderId: '235732561156',
    projectId: 'haber-cepte-b7666',
    storageBucket: 'haber-cepte-b7666.firebasestorage.app',
    iosBundleId: 'com.example.haberCepte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqdYE8anvzSzh6MvIcxUM8MYPDeEcPAmY',
    appId: '1:235732561156:web:bda9f3a6bcc8bc12177451',
    messagingSenderId: '235732561156',
    projectId: 'haber-cepte-b7666',
    authDomain: 'haber-cepte-b7666.firebaseapp.com',
    storageBucket: 'haber-cepte-b7666.firebasestorage.app',
  );
}
